name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
    paths-ignore:
    - "*.md"
    - LICENSE
    - "*.yaml"
  pull_request:
    branches:
      - master
    paths-ignore:
    - "*.md"
    - LICENSE
    - "*.yaml"


jobs:
  run-linters-mpw:
    name: Run linters (MPW)
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install Node.js dependencies
        working-directory: ./MPW
        run: npm ci

      - name: Run ESlint
        working-directory: ./MPW
        run: npm run lint
        
      - name: Run prettier
        working-directory: ./MPW
        run: npx prettier -l .
        
      - name: Run tests
        working-directory: ./MPW
        run: npm test
  run-linters-tauri:
    name: Run linters (Tauri)
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: Run tests
        working-directory: ./src-tauri
        run: cargo test --all-features

      - name: Check formatting
        uses: actions-rust-lang/rustfmt@v1
        working-directory: ./src-tauri

        
  build-tauri:
    name: Build tauri
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
          
      - name: Install Node.js dependencies
        run: npm ci

      - name: Build tauri
        run: npm run tauri build
      
          
